# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
# Based on
FROM jupyter/datascience-notebook:ubuntu-20.04

USER root

# install ros
# setup timezone
RUN apt-get update && \
    apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2  && \
    rm -rf /var/lib/apt/lists/*

# setup keys
RUN set -eux; \
    key='C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654'; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
    mkdir -p /usr/share/keyrings; \
    gpg --batch --export "$key" > /usr/share/keyrings/ros1-latest-archive-keyring.gpg; \
    gpgconf --kill all; \
    rm -rf "$GNUPGHOME"

# setup sources.list
RUN echo "deb [ signed-by=/usr/share/keyrings/ros1-latest-archive-keyring.gpg ] http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros1-latest.list

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV ROS_DISTRO noetic

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-noetic-robot \
    build-essential \
    python3-rosdep \
    python3-rosinstall \
    python3-vcstools \
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep
RUN rosdep init
# update rosdep
USER ${NB_UID}
RUN rosdep update --rosdistro $ROS_DISTRO

# # Source the ROS setup file
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc

# get ROS package sources for the course
USER root
RUN mkdir -p /home/${NB_USER}/catkin_ws/src && \
    cd /home/${NB_USER}/catkin_ws/src && \
    git clone https://github.com/Kinovarobotics/ros_kortex && \
    git clone https://github.com/AIResearchLab/sphero_rvr_ros

# update ROS dependencies
RUN apt-get update && \
    rosdep install --from-paths /home/${NB_USER}/catkin_ws/src --ignore-src -r -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Make sure the contents of our repo are in ${HOME}
RUN mkdir -p ${HOME}/work
COPY . ${HOME}/work

# install pip dependencies
RUN pip install --no-cache-dir -r ${HOME}/work/requirements.txt && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

USER ${NB_UID}
